version: "3"

services:
  api_blog:
    image: "jhonoryza/golang-blog-api:latest"
    container_name: "golang-blog-api"
    restart: unless-stopped
    ports:
      - 10200:8080
    env_file:
      - ./.env
